//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DSAKeyValue&gt;&lt;P&gt;jdb1ylhwpux5943fQms/U9zSAckXYBVet54X+uxMPF+g1oL2S50NQuElzG+pNzPDLdWkufDQy1yjtZX3q5IgL9x+O3RFh/WbVjvjaQu3izMgZmiTZzz5YlW+BWTw0EXOpwVrLtE3w/y/eXRJaRY+cl67TqTum2f9FX1PMmYWB4E=&lt;/P&gt;&lt;Q&gt;zTnBe+MaCGQuSThM3FVSd1iirL8=&lt;/Q&gt;&lt;G&gt;YPeeV6qpDowJRKHrYw+MvziM3dsO+S14mEj/jlGAyCmzChx04gVLrI2tcnONp4z6YutcOYBYTiD5vG5fpNFw/oRbNuNBSzRLRan3BPYQoF6yoI9dUZCQsKSkUncabt25/GoEB6uHchwzo5jt9GDyvkGgJHXEm3Vd1aI3S1ToidY=&lt;/G&gt;&lt;Y&gt;cnjQ4uotSLHuiyE/j/o7abSLIjIgxiABxzbq4rhvhJuF/8OcoLGkeJZWt9DHmV7Hbcp2YXNdZ57U3YIxBQ/GNVzTjVOLBQ9qazYaob9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string publicKey {
            get {
                return ResourceManager.GetString("publicKey", resourceCulture);
            }
        }
    }
}
